package com.settleiq;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Every pipeline stage is independently toggleable, because the ablation table
 * is the single most persuasive artifact this system produces and it has to be
 * generated by really turning components off -- not by estimating what they
 * contribute.
 */
public final class Config {
    // ---- stage toggles -------------------------------------------------------
    public boolean stageNormalise = true;
    public boolean stageUtrRepair = true;
    public boolean stageExactMatch = true;
    public boolean stageCandidateGen = true;
    public boolean stageScorer = true;
    public boolean stageGlobalAssignment = true;
    public boolean stageNetting = true;
    public boolean stageNettingDp = true;
    public boolean stageAgent = true;

    // ---- thresholds (tuned on DEV only; test is touched once) ---------------
    public long tolerancePaise = 100;              // +/- Rs 1.00
    public long amountWindowPaise = 50_00_000L;    // Rs 50,000 blocking window
    public int dateWindowBankingDays = 3;
    public double minAssignProbability = 0.55;
    public double ambiguityMargin = 0.08;
    public int dpMaxItems = 400;

    // ---- policy -------------------------------------------------------------
    public double autoPostMinConfidence = 0.95;
    public long autoPostMaxResiduePaise = 10_000L;      // Rs 100.00
    public double autoPostMaxResidueFraction = 0.001;   // 0.1% of batch value
    public long dailyAutoPostBudgetPaise = 50_00_000L;  // Rs 50,000 per day
    public int dailyAutoPostCountBudget = 60;
    public Set<String> autoPostAllowlist = new LinkedHashSet<>(java.util.List.of(
            "timing_offset", "netted_refund", "fee_variance", "reserve_movement",
            "rounding_drift"));

    /** When false the agent always uses its deterministic planner, whatever the
     *  environment says. Needed for reproducible runs and for any comparison
     *  that wants a model-free baseline to measure against. */
    public boolean llmPlanner = true;

    public String modelPath = "mlservice/model.json";
    public String auditPath = "reports/audit_ledger.jsonl";

    public static Config deterministicOnly() {
        Config c = new Config();
        c.stageScorer = false;
        c.stageGlobalAssignment = false;
        c.stageNetting = false;
        c.stageNettingDp = false;
        c.stageAgent = false;
        c.stageUtrRepair = false;
        return c;
    }

    public static Config plusRepair() {
        Config c = deterministicOnly();
        c.stageUtrRepair = true;
        return c;
    }

    public static Config plusScorer() {
        Config c = plusRepair();
        c.stageScorer = true;
        return c;
    }

    public static Config plusGlobalAssignment() {
        Config c = plusScorer();
        c.stageGlobalAssignment = true;
        return c;
    }

    public static Config plusNetting() {
        Config c = plusGlobalAssignment();
        c.stageNetting = true;
        c.stageNettingDp = true;
        return c;
    }

    /**
     * STRESS CONFIGURATIONS.
     *
     * On the default pipeline, exact-UTR and unique-repair matching resolve
     * most credits deterministically before the assignment problem is reached,
     * so greedy and Hungarian agree and global assignment shows no measurable
     * gain. That is a real result about THIS dataset, not evidence that global
     * assignment is worthless.
     *
     * These two presets remove the deterministic shortcuts so every credit must
     * be resolved through the scored candidate graph. That is the regime a
     * merchant with a worse bank feed actually lives in, and it is where the
     * one-to-one constraint either holds or does not.
     */
    public static Config stressGreedy() {
        Config c = full();
        c.stageExactMatch = false;
        c.stageUtrRepair = false;
        c.stageGlobalAssignment = false;
        return c;
    }

    public static Config stressGlobal() {
        Config c = stressGreedy();
        c.stageGlobalAssignment = true;
        return c;
    }

    public static Config full() {
        Config c = plusNetting();
        c.stageAgent = true;
        return c;
    }

    public String describe() {
        return "norm=" + stageNormalise + " repair=" + stageUtrRepair + " exact=" + stageExactMatch
                + " cand=" + stageCandidateGen + " scorer=" + stageScorer
                + " global=" + stageGlobalAssignment + " netting=" + stageNetting
                + " dp=" + stageNettingDp + " agent=" + stageAgent;
    }
}
